### ISSUE TITLE
`mir --version` causes "No module named '_ctypes'"

### ISSUE THREAD

**Issue by liyi93319** [IndustryEssentials/ymir#1320]
**Describe the issue**
I guess I've managed to install ymir command on my Ubuntu 18.04 with Python 3.9.15 since I got this log.

```
Installing collected packages: lmdb, xmltodict, urllib3, typing-extensions, six, pyyaml, py, protobuf, Pillow, numpy, idna, decorator, chardet, certifi, tensorboardX, retry, requests, pydantic, fasteners, ymir-cmd
Successfully installed Pillow-8.2.0 certifi-2022.9.24 chardet-4.0.0 decorator-5.1.1 fasteners-0.16.3 idna-2.10 lmdb-1.3.0 numpy-1.22.0 protobuf-3.18.1 py-1.11.0 pydantic-1.9.0 pyyaml-5.4.1 requests-2.25.1 retry-0.9.2 six-1.16.0 tensorboardX-2.4.1 typing-extensions-4.4.0 urllib3-1.26.12 xmltodict-0.12.0 ymir-cmd-2.0.0
```

However, the `mir --version` command just gives "No module named '_ctypes'" error.

```
Traceback (most recent call last):
  File "/home/dssapce/.local/bin/mir", line 5, in <module>
    from mir.main import main
  File "/home/dssapce/.local/lib/python3.9/site-packages/mir/main.py", line 2, in <module>
    from mir.cli import create_main_parser
  File "/home/dssapce/.local/lib/python3.9/site-packages/mir/cli.py", line 9, in <module>
    from mir.commands import (init, checkout, commit, copy, export, filter, merge,
  File "/home/dssapce/.local/lib/python3.9/site-packages/mir/commands/init.py", line 10, in <module>
    from mir.tools import checker, class_ids, mir_storage_ops, revs_parser
  File "/home/dssapce/.local/lib/python3.9/site-packages/mir/tools/mir_storage_ops.py", line 8, in <module>
    from google.protobuf import json_format
  File "/home/dssapce/.local/lib/python3.9/site-packages/google/protobuf/json_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/home/dssapce/.local/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 48, in <module>
    import ctypes
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes' 
```

Am I missing something?

**To Reproduce**

```
    wget https://www.python.org/ftp/python/3.9.15/Python-3.9.15.tgz
    tar xzf Python-3.9.15.tgz
    cd Python-3.9.15
    ./configure --enable-optimizations
    make install
    pip3 install ymir-cmd -i https://pypi.tuna.tsinghua.edu.cn/simple
    mir --version
```

**Comment by phoenix-xhuang** [comment]
try python 3.8.10

**Comment by liyi93319** [comment]
> try python 3.8.10

the same error

```
Traceback (most recent call last):
  File "/usr/local/bin/mir", line 5, in <module>
    from mir.main import main
  File "/usr/local/lib/python3.8/site-packages/mir/main.py", line 2, in <module>
    from mir.cli import create_main_parser
  File "/usr/local/lib/python3.8/site-packages/mir/cli.py", line 9, in <module>
    from mir.commands import (init, checkout, commit, copy, export, filter, merge,
  File "/usr/local/lib/python3.8/site-packages/mir/commands/init.py", line 10, in <module>
    from mir.tools import checker, class_ids, mir_storage_ops, revs_parser
  File "/usr/local/lib/python3.8/site-packages/mir/tools/mir_storage_ops.py", line 8, in <module>
    from google.protobuf import json_format
  File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/usr/local/lib/python3.8/site-packages/google/protobuf/internal/type_checkers.py", line 48, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

**Comment by fenrir-z** [comment]
what's your system version?
do you have libffi-dev installed?

see also:
https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul

**Comment by liyi93319** [comment]
> what's your system version? do you have libffi-dev installed?
> 
> see also: https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul

libffi-dev was the block, thanks to you, problem solved. appreciate it~
