### ISSUE TITLE
部分公共镜像推理失败

### ISSUE THREAD

**Issue by huu3301** [IndustryEssentials/ymir#1428]
Describe the bug
平台版本2.0.1，使用部分公共镜像推理失败。

To Reproduce

1、使用公共镜像youdaoyzbx/ymir-executor:ymir2.0.0-nanodet-cu111-tmi或者youdaoyzbx/ymir-executor:ymir2.0.0-mmdet-cu111-tmi （yolov4、yolov5、yolov7、detectron2、vidt镜像无此问题）。
2、训练。
3、训练完之后使用该模型进行推理（默认参数未修改），推理失败（如果GPU个数改成1则推理成功）

Traceback (most recent call last):
  File "ymir_infer.py", line 137, in <module>
    sys.exit(main())
  File "ymir_infer.py", line 109, in main
    model = YmirModel(cfg)
  File "ymir_infer.py", line 98, in __init__
    self.model = init_detector(config_file, checkpoint_file, device=f'cuda:{gpu_id}', cfg_options=cfg_options)
  File "/app/mmdet/apis/inference.py", line 54, in init_detector
    model.to(device)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Invalid device string: 'cuda:'

**Comment by yzbx** [comment]
> 

这两个镜像目前还不支持多GPU推理，bug已记录，待修复。

https://github.com/modelai/ymir-executor-fork/discussions/20
