### ISSUE TITLE
无法拉取公共镜像

### ISSUE THREAD

**Issue by FirokOtaku** [IndustryEssentials/ymir#1556]
尝试从 "镜像社区" 拉取公共镜像,
点击 "添加到我的镜像" 后,
"我的镜像" 页面内的镜像列表一直有红叉号标志.

![image](https://user-images.githubusercontent.com/13001378/218399651-4de77645-4c1d-4a24-afa3-fffd0ed631d3.png)

请问应如何排查问题?

--- | ---
--- | ---
YMIR 安装系统 | Ubuntu Desktop 22.04.1
Docker | 23.0.1
Docker Compose | 2.15.1
访问浏览器 | Chrome 109.0.5414.120

**Comment by phoenix-xhuang** [comment]
直接docker pull 镜像地址试试

**Comment by FirokOtaku** [comment]
> 直接docker pull 镜像地址试试

![image](https://user-images.githubusercontent.com/13001378/218411190-a9ee74f9-b5d0-441c-a13c-d5734384e13d.png)

直接拉取镜像没有问题.

**Comment by phoenix-xhuang** [comment]
看样子本地还没有镜像，也就是在拉取的过程中

**Comment by FirokOtaku** [comment]
> 看样子本地还没有镜像，也就是在拉取的过程中

请问有地方可以查看拉取进度之类的日志吗?

![image](https://user-images.githubusercontent.com/13001378/218615363-2ed97ab3-ddee-4a4b-80ab-a999595ac5cc.png)

宿主机执行命令之后已经拉取好了, 
但是 ymir 系统里一直是红叉号没动静.

**Comment by yzbx** [comment]
# 测试环境

## 查看系统版本 `lsb_release -a`
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

## 查看docker版本 `docker --version`
```
Docker version 23.0.1, build a5ee5b1
```

## 查看docker-compose版本 `docker-compose --version  `
```
docker-compose version 1.29.2, build 5becea4c
```

## 查看glibc版本 `ldd --version`
```                                                           
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

## 测试镜像 `docker run --rm youdaoyzbx/ymir-executor:ymir2.0.0-mmdet-cu111-tmi ls /img-man`
```
infer-template.yaml
mining-template.yaml
training-template.yaml
```

## 测试ymir

![mmdet](https://user-images.githubusercontent.com/5005182/218629021-43196da7-627b-4f38-981e-2c481a46f2b3.png)

**Comment by FirokOtaku** [comment]
> # 测试环境
> ...


`lsb_release -a`

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

`docker --version`

```
Docker version 23.0.1, build a5ee5b1
```

`docker-compose --version`

```
Docker Compose version v2.15.1
```

`ldd --version`

```
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 自由软件基金会。
这是一个自由软件；请见源代码的授权条款。本软件不含任何没有担保；甚至不保证适销性
或者适合某些特殊目的。
由 Roland McGrath 和 Ulrich Drepper 编写。
```

`docker run --rm youdaoyzbx/ymir-executor:ymir2.0.0-mmdet-cu111-tmi ls /img-man`

```
infer-template.yaml
mining-template.yaml
training-template.yaml
```

**Comment by FirokOtaku** [comment]
检查 `ymir/ymir-workspace/ymir-data/logs/ymir_app.log` 内容发现如下报错:

```
[2023-02-14 07:08:29 +0000] [152] [INFO] 172.19.0.7:45218 - "GET /api/v1/images/?url=youdaoyzbx%2Fymir-executor:ymir2.0.0-mmdet-cu111-tmi&limit=10&offset=0 HTTP/1.0" 200
INFO: [20230214-07:08:31] images.py:68 : [create image] docker image record created: <app.models.image.DockerImage object at 0x7f7af86963a0>
[2023-02-14 07:08:31 +0000] [152] [INFO] 172.19.0.7:45220 - "POST /api/v1/images/ HTTP/1.0" 200
INFO: [20230214-07:08:31] ymir_controller.py:383: [controller] request: user_id: "0001"
repo_id: "000000"
req_type: CMD_PULL_IMAGE
task_id: "t00000010000001495011676358511"
singleton_op: "youdaoyzbx/ymir-executor:ymir2.0.0-mmdet-cu111-tmi"

ERROR: [20230214-07:08:31] images.py:87 : [create image] failed to import docker image via controller
Traceback (most recent call last):
  File "/app/ymir_app/app/api/api_v1/endpoints/images.py", line 85, in import_docker_image
    resp = controller_client.pull_docker_image(docker_image.url, user_id)
  File "/app/ymir_app/app/utils/ymir_controller.py", line 460, in pull_docker_image
    return self.send(req)
  File "/app/ymir_app/app/utils/ymir_controller.py", line 387, in send
    self.check_response_code(resp.code, resp.message, verbose)
  File "/app/ymir_app/app/utils/ymir_controller.py", line 380, in check_response_code
    raise ValueError(f"gRPC error. response: {resp_code} {resp_msg}")
ValueError: gRPC error. response: 130401 docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
```

检查 `ymir/ymir-workspace/ymir-data/logs/ymir_controller.log` 内容发现如下报错:

```
INFO: [20230214-03:13:33] invoker_cmd_base.py:80 :	task_id: t0000001000000bc51e71676344413 req_type: 16
INFO: [20230214-03:13:33] utils.py:26 :	starting cmd: 
docker image inspect youdaoyzbx/ymir-executor:ymir2.0.0-mmdet-cu111-tmi --format ignore_me

ERROR: [20230214-03:13:33] utils.py:29 :	run cmd error:
 stderr: docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
 
 stdout: 
INFO: [20230214-03:13:33] utils.py:26 :	starting cmd: 
docker pull youdaoyzbx/ymir-executor:ymir2.0.0-mmdet-cu111-tmi

ERROR: [20230214-03:13:33] utils.py:29 :	run cmd error:
 stderr: docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
 
 stdout: 
INFO: [20230214-03:13:33] invoker_cmd_base.py:88 :	task id: t0000001000000bc51e71676344413 response: code: 130401 message: "docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32\' not found (required by docker)\ndocker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34\' not found (required by docker)\n"
INFO: [20230214-03:13:33] utils.py:96 :	|-server_invoke costs 0.00s(0.00m).
```

**Comment by FirokOtaku** [comment]
尝试跟随 GLIBC 官方 [安装文档](https://sourceware.org/glibc/wiki/Testing/Builds#Building_glibc_with_intent_to_install) 步骤重新安装 GLIBC, 拉取 Linux Kernel 仓库步骤 (`git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`) 过慢, 暂时放弃尝试.

**Comment by yzbx** [comment]
> 尝试跟随 GLIBC 官方 [安装文档](https://sourceware.org/glibc/wiki/Testing/Builds#Building_glibc_with_intent_to_install) 步骤重新安装 GLIBC, 拉取 Linux Kernel 仓库步骤 (`git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`) 过慢, 暂时放弃尝试.

建议降低系统版本至 ubuntu18.04，之前有用户通过此法解决glibc的问题。

**Comment by yzbx** [comment]
> 尝试跟随 GLIBC 官方 [安装文档](https://sourceware.org/glibc/wiki/Testing/Builds#Building_glibc_with_intent_to_install) 步骤重新安装 GLIBC, 拉取 Linux Kernel 仓库步骤 (`git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`) 过慢, 暂时放弃尝试.

docker-compose 的版本也可能是问题，参考 https://github.com/docker/compose/issues/8048

**Comment by FirokOtaku** [comment]
> 建议降低系统版本至 ubuntu18.04，之前有用户通过此法解决glibc的问题。

> docker-compose 的版本也可能是问题，参考 https://github.com/docker/compose/issues/8048

经测试, 降级安装 Ubuntu Desktop 18.04.6 并完整重装环境后可以正常拉取镜像.

`lsb_release -a`

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

`docker --version`

```
Docker version 23.0.1, build a5ee5b1
```

`docker-compose --version`

```
Docker Compose version v2.15.1
```

`ldd --version`

```
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Copyright (C) 2018 自由软件基金会。
这是一个自由软件；请见源代码的授权条款。本软件不含任何没有担保；甚至不保证适销性
或者适合某些特殊目的。
由 Roland McGrath 和 Ulrich Drepper 编写。
```

**Comment by yzbx** [comment]
此法经测试，无效。

~对于ubuntu 22.04+，如出现glibc找不到的错误，可以尝试重新构建镜像：~

```
DOCKER_BACKEND='industryessentials/ymir-backend:release-2.1.0'
DOCKER_WEB='industryessentials/ymir-web:release-2.1.0'
DEV_SOURCE_BACKEND_PIP='https://pypi.mirrors.ustc.edu.cn/simple'
DEV_SOURCE_WEB_NPM='https://registry.npmmirror.com'

printf '\nin dev mode, building images.\n'
docker build \
	-t ${DOCKER_BACKEND} \
	--build-arg PIP_SOURCE=${DEV_SOURCE_BACKEND_PIP} \
	https://github.com/IndustryEssentials/ymir.git#master:/ymir -f Dockerfile.backend
docker build \
	-t ${DOCKER_WEB} \
	--build-arg NPM_REGISTRY=${DEV_SOURCE_WEB_NPM} \
	https://github.com/IndustryEssentials/ymir.git#master:/ymir/web
```

再重新启动ymir后台服务
```
# 关闭服务
docker-compose down -v
# 重启服务
docker-compose up -d
```

**Comment by lszxyz** [comment]
backend 基础镜像debian， dockefile里面新增docker-ce-cli，重新build，docker-compose 注释 /usr/bin/docker 。

**Comment by zhangJoel** [comment]
> backend 基础镜像debian， dockefile里面新增docker-ce-cli，重新build，docker-compose 注释 /usr/bin/docker 。

您好，请问可以再说细一点吗？backend 基础镜像debian， dockefile里面新增docker-ce-cli 这两个具体怎么操作呢，非常感谢🙏
