### ISSUE TITLE
无法对示例项目的初始模型进行模型验证

### ISSUE THREAD

**Issue by FirokOtaku** [IndustryEssentials/ymir#1567]
在系统中创建示例项目, 对初始模型进行验证操作,
[上传图片] 并点击 [模型验证], 置信度拉到 100%, 其余全部使用默认设置,
会提示 "调用推理失败".

![image](https://user-images.githubusercontent.com/13001378/219301240-a63d1af0-5196-42e6-872a-3623d802c157.png)

![image](https://user-images.githubusercontent.com/13001378/219302046-4638c2e6-8522-4d98-9512-88255a3afca1.png)

查看 `/ymir/ymir-workspace/ymir-data/logs/ymir_app.log` 发现如下报错

```
INFO: [20230216-07:52:53] ymir_controller.py:383: [controller] request: user_id: "0001"
repo_id: "000004"
req_type: CMD_INFERENCE
task_id: "t00000010000041282a11676533973"
singleton_op: "industryessentials/executor-example:latest"
model_hash: "b8257bfae5481e6f3ff9c3e41e0726398cff9abb"
asset_dir: "/ymir-sharing/import_files_dhqfa9i3"
docker_image_config: "{\"idle_seconds\": 3, \"type\": 9}"
model_stage: "default_best_stage"

ERROR: [20230216-07:52:53] inferences.py:61 : Failed to call inference via Controller: gRPC error. response: 130401 Inference result not found: /home/user/ymir/ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t00000010000041282a11676533973/out/prediction.mir
Traceback (most recent call last):
  File "/app/ymir_app/app/api/api_v1/endpoints/inferences.py", line 51, in call_inference
    resp = controller_client.call_inference(
  File "/app/ymir_app/app/utils/ymir_controller.py", line 517, in call_inference
    return self.send(req)
  File "/app/ymir_app/app/utils/ymir_controller.py", line 387, in send
    self.check_response_code(resp.code, resp.message, verbose)
  File "/app/ymir_app/app/utils/ymir_controller.py", line 380, in check_response_code
    raise ValueError(f"gRPC error. response: {resp_code} {resp_msg}")
ValueError: gRPC error. response: 130401 Inference result not found: /home/user/ymir/ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t00000010000041282a11676533973/out/prediction.mir
[2023-02-16 07:52:53 +0000] [137] [INFO] 172.19.0.7:58754 - "POST /api/v1/inferences/ HTTP/1.0" 200
```

请问是操作流程有误还是其它什么原因?

> 系统环境跟 [前次 issue](https://github.com/IndustryEssentials/ymir/issues/1556#issuecomment-1432590541) 一样, 是全新安装的 Ubuntu Desktop 18.04.6.

**Comment by fenrir-z** [comment]
在 `ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t00000010000041282a11676533973/out/ymir-executor-out.log` 里面有发现报错信息吗？

**Comment by yzbx** [comment]
无法复现你的问题，但sampel_image 产生的map 应该固定为0.983, 为什么你的是0.683
![图片](https://user-images.githubusercontent.com/5005182/219354242-f3525baa-a388-43c6-9081-e8c62a80800b.png)

![图片](https://user-images.githubusercontent.com/5005182/219354703-f39ea782-df12-4bd5-8f10-52ea388e0d43.png)

**Comment by FirokOtaku** [comment]
> 在 `ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t00000010000041282a11676533973/out/ymir-executor-out.log` 里面有发现报错信息吗？

检查此文件内容为空.

> 无法复现你的问题，但sampel_image 产生的map 应该固定为0.983, 为什么你的是0.683

不清楚.

**Comment by phoenix-xhuang** [comment]
再跑一次，可以在ymir-workplace/sandbox/work_dir/CMD_INFERENCE目录下找到和任务相关的日志

**Comment by FirokOtaku** [comment]
> 再跑一次，可以在ymir-workplace/sandbox/work_dir/CMD_INFERENCE目录下找到和任务相关的日志

这个周暂时不方便做更多测试, 更多的得下周做了.
但是有印象 `ymir-workplace/sandbox/work_dir/CMD_INFERENCE` 目录下还有几个别的目录,
子目录里的 `out/ymir-executor-out.log` 都是空的.

**Comment by fenrir-z** [comment]
如果这个里面是空的话，很可能镜像本身没有启动。
请查看 ymir-workplace/ymir-data/logs/ymir_controller.log 里面，查找一下关键字 nvidia-docker run，看一下有没有相关的报错日志，也请注意一下这个 nvidia-docker run 和下一条日志的间隔时间是不是非常短。
另外，这个镜像你是否有修改过？

**Comment by FirokOtaku** [comment]
> 请查看 ymir-workplace/ymir-data/logs/ymir_controller.log 里面，查找一下关键字 nvidia-docker run，看一下有没有相关的报错日志，也请注意一下这个 nvidia-docker run 和下一条日志的间隔时间是不是非常短。

有报错; 间隔非常短.

```
INFO: [20230216-06:48:25] utils.py:26 :	starting cmd: 
mir mining --root /home/user/ymir/ymir-workplace/sandbox/0001/000001 --user-label-file /home/user/ymir/ymir-workplace/sandbox/0001/labels.yaml --dst-rev t0000001000001ff72c71676530105@t0000001000001ff72c71676530105 -w /home/user/ymir/ymir-workplace/sandbox/work_dir/TaskTypeMining/t0000001000001ff72c71676530105/sub_task/t0000001000001ff72c71676530105 --model-location /home/user/ymir/ymir-workplace/ymir-models --media-location /home/user/ymir/ymir-workplace/ymir-assets --model-hash 29306cf5faafbd6d0b9626ae41b8961ac1aff62a@default_best_stage --src-revs t0000001000001fbc0571676530064 -s host --asset-cache-dir /home/user/ymir/ymir-workplace/sandbox/0001/asset_cache --task-config-file /home/user/ymir/ymir-workplace/sandbox/work_dir/TaskTypeMining/t0000001000001ff72c71676530105/sub_task/t0000001000001ff72c71676530105/task_config.yaml --executor industryessentials/executor-example:latest --executant-name t0000001000001ff72c71676530105 --topk 1 --add-prediction

ERROR: [20230216-06:48:26] utils.py:29 :	run cmd error:
 stderr: Traceback (most recent call last):
  File "/usr/local/bin/mir", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/mir/main.py", line 19, in main
    return cmd.cmd_run()
  File "/usr/local/lib/python3.8/site-packages/mir/tools/code.py", line 34, in wrapper
    _ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mir/commands/base.py", line 16, in cmd_run
    return self.run()
  File "/usr/local/lib/python3.8/site-packages/mir/commands/mining.py", line 33, in run
    return CmdMining.run_with_args(work_dir=self.args.work_dir,
  File "/usr/local/lib/python3.8/site-packages/mir/tools/command_run_in_out.py", line 168, in wrapper
    raise exc
PermissionError: [Errno 13] Permission denied: 'nvidia-docker'
 
 stdout: INFO: [20230216-06:48:26] code.py:36 : |-export_mirdatas_to_dir costs 0.00s(0.00m).
INFO: [20230216-06:48:26] models.py:148: extracting models: /home/user/ymir/ymir-workplace/ymir-models/29306cf5faafbd6d0b9626ae41b8961ac1aff62a, stage: default_best_stage
```

> 另外，这个镜像你是否有修改过？

没有, ymir 环境是全新安装的.

**Comment by phoenix-xhuang** [comment]
这个报错信息是运行不了nvidia-docker，所以推理会失败。
请在命令行运行下直接nvidia-docker，并解决遇到的问题后再重试

**Comment by FirokOtaku** [comment]
`sudo apt-get install nvidia-docker2` 之后再次尝试执行验证模型,
等待一段时间后界面提示 "网关请求超时, 后端服务异常"

![image](https://user-images.githubusercontent.com/13001378/220036742-e135e71f-2ed4-416c-83e2-79870b148323.png)

`app_controller.log` 内容如下

```
INFO: [20230220-07:06:29] server.py:89 :	env empty for key: OPENPAI_HOST
INFO: [20230220-07:06:29] server.py:89 :	env empty for key: OPENPAI_TOKEN
INFO: [20230220-07:06:29] server.py:89 :	env empty for key: OPENPAI_STORAGE
INFO: [20230220-07:06:29] server.py:89 :	env empty for key: OPENPAI_USER
INFO: [20230220-07:06:29] server.py:89 :	env empty for key: OPENPAI_CLUSTER
INFO: [20230220-07:06:29] server.py:89 :	env empty for key: OPENPAI_GPUTYPE
INFO: [20230220-07:06:29] metrics.py:14 :	Metrics init: perm-False uuid-testdev host-ymir.ai port-9125
INFO: [20230220-07:06:30] server.py:141:	mir controller started, sandbox root: /home/user/ymir/ymir-workplace/sandbox, port: 50066
INFO: [20230220-07:06:31] invoker_cmd_base.py:80 :	task_id: t00000000000006fbf6a1676876791 req_type: 22
INFO: [20230220-07:06:31] invoker_cmd_base.py:88 :	task id: t00000000000006fbf6a1676876791 response: sandbox_versions: "2.0.0"
INFO: [20230220-07:06:31] utils.py:96 :	|-server_invoke costs 0.00s(0.00m).
INFO: [20230220-07:06:33] invoker_cmd_base.py:80 :	task_id: t0000001000004d1973e1676876793 req_type: 21
INFO: [20230220-07:06:33] invoker_cmd_base.py:80 :	task_id: t0000001000004d1973e1676876793 req_type: 20
INFO: [20230220-07:06:33] invoker_cmd_base.py:80 :	task_id: t0000001000002e5f81b1676876793 req_type: 21
INFO: [20230220-07:06:33] invoker_cmd_base.py:80 :	task_id: t0000001000002e5f81b1676876793 req_type: 20
INFO: [20230220-07:06:34] invoker_cmd_base.py:88 :	task id: t0000001000004d1973e1676876793 response: ops_ret: true
INFO: [20230220-07:06:34] utils.py:96 :	|-server_invoke costs 0.30s(0.00m).
INFO: [20230220-07:06:34] invoker_cmd_base.py:88 :	task id: t0000001000004d1973e1676876793 response: ops_ret: true
INFO: [20230220-07:06:34] utils.py:96 :	|-server_invoke costs 0.30s(0.00m).
INFO: [20230220-07:06:34] invoker_cmd_base.py:88 :	task id: t0000001000002e5f81b1676876793 response: ops_ret: true
INFO: [20230220-07:06:34] utils.py:96 :	|-server_invoke costs 0.31s(0.01m).
INFO: [20230220-07:06:34] invoker_cmd_base.py:88 :	task id: t0000001000002e5f81b1676876793 response: ops_ret: true
INFO: [20230220-07:06:34] utils.py:96 :	|-server_invoke costs 0.31s(0.01m).
INFO: [20230220-07:06:54] invoker_cmd_base.py:80 :	<class 'controller.invoker.invoker_cmd_inference.InferenceCMDInvoker'>
 request: {'user_id': '0001', 'repo_id': '000004', 'req_type': 11, 'task_id': 't0000001000004a4cb811676876814', 'singleton_op': 'industryessentials/executor-example:latest', 'model_hash': 'b8257bfae5481e6f3ff9c3e41e0726398cff9abb', 'asset_dir': '/ymir-sharing/import_files_6cb73_92', 'docker_image_config': '{"idle_seconds": 3, "type": 9}', 'model_stage': 'default_best_stage'}
 assets_config: {'assetskvlocation': '/home/user/ymir/ymir-workplace/ymir-assets', 'assetskvprotocol': 'file', 'assetsuploadlocation': '/home/user/ymir/ymir-workplace/ymir-assets', 'assetsuploadprotocol': 'file', 'modelskvlocation': '/home/user/ymir/ymir-workplace/ymir-models', 'modelskvprotocol': 'file', 'modelsuploadlocation': '/home/user/ymir/ymir-workplace/ymir-models', 'modelsuploadprotocol': 'file', 'tensorboard_root': '/home/user/ymir/ymir-workplace/ymir-tensorboard-logs', 'openpai_host': '', 'openpai_token': '', 'openpai_storage': '', 'openpai_user': '', 'openpai_cluster': '', 'openpai_gputype': '', 'server_runtime': 'nvidia'}
 async_mode: True
 work_dir: /home/user/ymir/ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t0000001000004a4cb811676876814
INFO: [20230220-07:06:54] utils.py:26 :	starting cmd: 
mir infer --root /home/user/ymir/ymir-workplace/sandbox/0001/000004 --user-label-file /home/user/ymir/ymir-workplace/sandbox/0001/labels.yaml -w /home/user/ymir/ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t0000001000004a4cb811676876814 --model-location /home/user/ymir/ymir-workplace/ymir-models --index-file /home/user/ymir/ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t0000001000004a4cb811676876814/index.txt --model-hash b8257bfae5481e6f3ff9c3e41e0726398cff9abb@default_best_stage --task-config-file /home/user/ymir/ymir-workplace/sandbox/work_dir/CMD_INFERENCE/t0000001000004a4cb811676876814/inference_config.yaml --executor industryessentials/executor-example:latest
```

**Comment by phoenix-xhuang** [comment]
这里日志并没有报错，安装了nvidia-docker重启了ymir服务吗

**Comment by FirokOtaku** [comment]
应该是没重启的问题了, 现在点界面有正常反应了.
