### ISSUE TITLE
网关异常，无法连接到后端服务

### ISSUE THREAD

**Issue by wangchao1980** [IndustryEssentials/ymir#1676]
![image](https://user-images.githubusercontent.com/28770548/227111855-b7b7d4a6-057d-4d76-8537-fdd836ecaad5.png)

第一次部署咱们的系统，出现网关异常，无法连接到后端服务

**Comment by phoenix-xhuang** [comment]
1. 运行docker ps -a，查看相关镜像有没有问题
2. 如果镜像都启动了，查看ymir-workplace/ymir-data/logs下面的app/controller/hel日志有没有报错

**Comment by mujinsong** [comment]
> ![image](https://user-images.githubusercontent.com/28770548/227111855-b7b7d4a6-057d-4d76-8537-fdd836ecaad5.png)
> 
> 第一次部署咱们的系统，出现网关异常，无法连接到后端服务

你好，我也遇到了这个问题，问题是因为你的端口设置问题，把docker-compose.yml的nginx-port改成你env的nginx-port即可

**Comment by wangchao1980** [comment]
INFO: [20230324-02:52:52] ymir_controller.py:393: [controller] successfully get response: 
INFO: [20230324-02:52:52] check_mir_repo_version.py:57 : [start up] mir version check passed.
2023-03-24 02:52:53,140 - __main__ - INFO - Initializing service
2023-03-24 02:52:53,147 - __main__ - INFO - Service finished initializing
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> f05268b15d34, init tables
INFO: [20230324-02:52:55] initial_data.py:43 : Creating initial data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app/initial_data.py", line 60, in <module>
    main(base_alembic_revision)
  File "app/initial_data.py", line 44, in main
    init()
  File "app/initial_data.py", line 19, in init
    init_db(db)
  File "/app/ymir_app/app/db/init_db.py", line 22, in init_db
    docker_images = crud.docker_image.get_multi(db)
  File "/app/ymir_app/app/crud/base.py", line 64, in get_multi
    return db.query(self.model).offset(offset).limit(limit).all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2709, in all
    return self._iter().all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2844, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'")
[SQL: SELECT docker_image.id AS docker_image_id, docker_image.name AS docker_image_name, docker_image.url AS docker_image_url, docker_image.hash AS docker_image_hash, docker_image.description AS docker_image_description, docker_image.state AS docker_image_state, docker_image.enable_livecode AS docker_image_enable_livecode, docker_image.object_type AS docker_image_object_type, docker_image.is_shared AS docker_image_is_shared, docker_image.is_deleted AS docker_image_is_deleted, docker_image.create_datetime AS docker_image_create_datetime, docker_image.update_datetime AS docker_image_update_datetime 
FROM docker_image 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'param_1': 0, 'param_2': 20}]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by wangchao1980** [comment]
INFO: [20230324-02:52:52] ymir_controller.py:393: [controller] successfully get response: 
INFO: [20230324-02:52:52] check_mir_repo_version.py:57 : [start up] mir version check passed.
2023-03-24 02:52:53,140 - __main__ - INFO - Initializing service
2023-03-24 02:52:53,147 - __main__ - INFO - Service finished initializing
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> f05268b15d34, init tables
INFO: [20230324-02:52:55] initial_data.py:43 : Creating initial data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app/initial_data.py", line 60, in <module>
    main(base_alembic_revision)
  File "app/initial_data.py", line 44, in main
    init()
  File "app/initial_data.py", line 19, in init
    init_db(db)
  File "/app/ymir_app/app/db/init_db.py", line 22, in init_db
    docker_images = crud.docker_image.get_multi(db)
  File "/app/ymir_app/app/crud/base.py", line 64, in get_multi
    return db.query(self.model).offset(offset).limit(limit).all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2709, in all
    return self._iter().all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2844, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'")
[SQL: SELECT docker_image.id AS docker_image_id, docker_image.name AS docker_image_name, docker_image.url AS docker_image_url, docker_image.hash AS docker_image_hash, docker_image.description AS docker_image_description, docker_image.state AS docker_image_state, docker_image.enable_livecode AS docker_image_enable_livecode, docker_image.object_type AS docker_image_object_type, docker_image.is_shared AS docker_image_is_shared, docker_image.is_deleted AS docker_image_is_deleted, docker_image.create_datetime AS docker_image_create_datetime, docker_image.update_datetime AS docker_image_update_datetime 
FROM docker_image 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'param_1': 0, 'param_2': 20}]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by wangchao1980** [comment]
pymysql.err.OperationalError: (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'")
缺少字段

**Comment by mujinsong** [comment]
> pymysql.err.OperationalError: (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'") 缺少字段

docker ps看看

**Comment by wangchao1980** [comment]
![image](https://user-images.githubusercontent.com/28770548/227420339-a5945127-30db-4ef2-a2c4-84efc6b039e8.png)

**Comment by mujinsong** [comment]
> ![image](https://user-images.githubusercontent.com/28770548/227420339-a5945127-30db-4ef2-a2c4-84efc6b039e8.png)

是的，我也是这个容器unhealthy，联系官方人员吧

**Comment by wangchao1980** [comment]
是初始化数据报错了，我看看代码

**Comment by wangchao1980** [comment]
@phoenix-xhuang pymysql.err.OperationalError: (1054, "Unknown column 'docker_image.enable_livecode' in 'field list'")
缺少字段

**Comment by phoenix-xhuang** [comment]
我们重现了上述问题，一些并行进程资源竞争会偶尔造成新部署/升级失败。会在pr 1679中解决，正在进行测试

https://github.com/IndustryEssentials/ymir/pull/1679

**Comment by wangchao1980** [comment]
好的，辛苦，谢谢

**Comment by trustfuture** [comment]
2.4.0 最新版本，仍然出现上述问题

**Comment by No33109** [comment]
最新版本，依然是这样
