### ISSUE TITLE
多模态大模型无法训练

### ISSUE THREAD

**Issue by JankinHou** [IndustryEssentials/ymir#1770]
我在使用多模态大模型进行训练的时候，训练失败，报错 160011，CMD: 无结果生成
查看ymir-executor-out.log  没有明显报错
ymir_app.log报错如下：

INFO: [20230726-02:46:40] ymir_viz.py:514: [viewer] request url http://127.0.0.1:9527/api/v1/users/0001/repo/000018/branch/t0000001000018583fc71690339529/model_info and params None
ERROR: [20230726-02:46:40] ymir_viz.py:538: [viewer] error response: b'{"code":180100,"msg":"invalid model","success":false,"result":{"code":180100,"msg":"invalid model"}}'
ERROR: [20230726-02:46:40] tasks.py:201: [update task] failed to get model_info: unknown error
Traceback (most recent call last):
  File "/app/ymir_app/app/libs/tasks.py", line 196, in model_info
    result = self.viz.get_model_info(self.task_hash)
  File "/app/ymir_app/app/utils/ymir_viz.py", line 373, in get_model_info
    res = self.parse_resp(resp)
  File "/app/ymir_app/app/utils/ymir_viz.py", line 544, in parse_resp
    raise FailedToParseVizResponse()
app.api.errors.errors.FailedToParseVizResponse
INFO: [20230726-02:46:40] tasks.py:340: [update task] updating task state TaskState.error and percent 1.0
INFO: [20230726-02:46:40] tasks.py:242: notify task update ({'t0000001000018583fc71690339529': {'task_id': 't0000001000018583fc71690339529', 'timestamp': 1690339600.929291, 'percent': 1.0, 'state': 4, 'result_state': <ResultState.error: 2>, 'result_model': {'id': 11, 'model_group_id': 5, 'result_state': <ResultState.error: 2>, 'result_type': <ResultType.model: 2>}, 'result_dataset': None, 'result_prediction': None, 'result_docker_image': None}}) to frontend (/0001)
[2023-07-26 02:46:40 +0000] [22421] [INFO] 127.0.0.1:53022 - "POST /api/v1/tasks/status HTTP/1.1" 200

ymir_controller.log报错如下：

ERROR: [20230726-02:46:22] utils.py:37 :     run cmd error:
 stderr: Traceback (most recent call last):
  File "/usr/local/bin/mir", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/mir/main.py", line 19, in main
    return cmd.cmd_run()
  File "/usr/local/lib/python3.8/site-packages/mir/tools/code.py", line 35, in wrapper
    _ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mir/commands/base.py", line 16, in cmd_run
    return self.run()
  File "/usr/local/lib/python3.8/site-packages/mir/commands/training.py", line 125, in run
    return CmdTrain.run_with_args(work_dir=self.args.work_dir,
  File "/usr/local/lib/python3.8/site-packages/mir/tools/command_run_in_out.py", line 172, in wrapper
    raise exc
mir.tools.errors.MirRuntimeError: code: 160011, message: [Errno 2] No such file or directory: '/home/project/ymir/ymir-workplace/sandbox/work_dir/TaskTypeTraining/t0000001000018583fc71690339529/sub_task/t0000001000018583fc71690339529/out/models/result.yaml'

 stdout: INFO: [20230726-02:45:30] merge.py:103: Merged va:t0000001000018c45b821690266109, total assets: 100

系统环境是：
Ubuntu 20.04
ymir2.5
训练镜像：industryessentials/ymir-executor:ymir2.5.0-glip-1.0-tmi

**Comment by phoenix-xhuang** [comment]
检查镜像产生的executor-log
