### ISSUE TITLE
Failed to start a training task

### ISSUE THREAD

**Issue by vs555** [IndustryEssentials/ymir#338]
![image](https://user-images.githubusercontent.com/42991662/156285920-52a8d732-72a6-44af-b110-672f80cf82b8.png)

**Comment by fenrir-z** [comment]
hello, i found error log here:
```
ERROR   : [20220302-02:52:53] utils.py:23:run_command(): run cmd error:
 Traceback (most recent call last):
  File "/usr/local/bin/mir", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mir/main.py", line 19, in main
    return cmd.cmd_run()
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/utils.py", line 24, in wrapper
    _ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/base.py", line 17, in cmd_run
    return self.run()
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/training.py", line 217, in run
    return CmdTrain.run_with_args(work_dir=self.args.work_dir,
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/command_run_in_out.py", line 135, in wrapper
    raise exc
PermissionError: [Errno 13] Permission denied: 'nvidia-docker'
```
please confirm:
1. is this user in `docker` group?
2. is nvidia-docker installed?

**Comment by ChinaRush** [comment]
@fenrir-z hi, I meet the same error, and my log is:

ERROR   : [20220518-01:37:13] app.py:59:handle_exception(): (['git', 'rev-parse', 't000000200001257c83b1652837818@t000000200001257c83b1652837818:tasks.mir'], 128, b"fatal: Invalid object name 't000000200001257c83b1652837818@t000000200001257c83b1652837818'.", b't000000200001257c83b1652837818@t000000200001257c83b1652837818:tasks.mir')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/dist-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/dist-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/usr/local/lib/python3.8/dist-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/app/ymir_viz/src/controllers/model_controller.py", line 22, in get_model_info
    model_info = pb_reader.MirStorageLoader(
  File "/app/ymir_viz/src/viz_models/pb_reader.py", line 21, in get_model_info
    model_info = mir_storage_ops.MirStorageOps.load_single_model(
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/mir_storage_ops.py", line 254, in load_single_model
    mir_storage_data: mirpb.MirTasks = cls.load_single_storage(mir_root=mir_root,
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/mir_storage_ops.py", line 220, in load_single_storage
    mir_storage_data.ParseFromString(exodus.read_mir(mir_root=mir_root, rev=rev,
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/exodus.py", line 18, in read_mir
    blob_hash = scm_git.rev_parse(f"{rev}:{file_name}")
  File "/usr/local/lib/python3.8/dist-packages/mir/scm/cmd.py", line 135, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mir/scm/cmd.py", line 439, in _call_process
    return self.execute(call, **exec_kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mir/scm/cmd.py", line 345, in execute
    raise ValueError(command, status, stderr_value, stdout_value)
ValueError: (['git', 'rev-parse', 't000000200001257c83b1652837818@t000000200001257c83b1652837818:tasks.mir'], 128, b"fatal: Invalid object name 't000000200001257c83b1652837818@t000000200001257c83b1652837818'.", b't000000200001257c83b1652837818@t000000200001257c83b1652837818:tasks.mir')
127.0.0.1 - - [18/May/2022:01:37:13 +0000] "GET /v1/users/0002/repositories/000012/branches/t000000200001257c83b1652837818/models HTTP/1.1" 500 305 "-" "python-requests/2.27.1"

![Screenshot from 2022-05-18 17-51-14](https://user-images.githubusercontent.com/39917677/169013164-a1a2246c-272b-4294-8bea-042297d9108b.png)
![Screenshot from 2022-05-18 17-57-13](https://user-images.githubusercontent.com/39917677/169013194-d61c1cdf-914f-4e74-8eb6-79b9780deb4e.png)
![Screenshot from 2022-05-18 17-57-36](https://user-images.githubusercontent.com/39917677/169013216-1e81eef6-1789-4136-a9d6-46033b3f7b52.png)



How to fixed this bug

**Comment by phoenix-xhuang** [comment]
Merge error happened in training task means there are conflict between training/validation dataset. Some of the test examples may already exist in training dataset. Please double check before proceed.

Tip: to exclude training samples from test dataset, 
1. try a data process task (预处理), 
2. choose test dataset,
3. exclude training dataset
 The result dataset will remove all examples belonging to training dataset.
