### ISSUE TITLE
训练一段时间后，中途失败了，显示未知错误

### ISSUE THREAD

**Issue by zandb2009** [IndustryEssentials/ymir#909]
[**Describe the bug**
训练一段时间后(大概一天左右)后失败了，显示未知错误
训练数据是2500张图片，测试数据是200张。
用的显卡是 RTX3050 8G  训练时修改过参数 batch 从64修改为16   图片尺寸参数从608----608修改为416----416

训练错误日志ymir-executor-out.log如下：
2022-07-07 04:35:28,817 - /darknet/train_watcher.py[line:43] - ERROR: error occured in handler: <function _DarknetTrainingHandler._on_best_weights_modified at 0x7ff41bca5830> and path: /out/models/yolov4_best.weights
Traceback (most recent call last):
  File "/darknet/train_watcher.py", line 41, in on_modified
    handler(self, src_path)
  File "/darknet/train_watcher.py", line 52, in _on_best_weights_modified
    export_dir='/out/models')
  File "/darknet/convert_model_darknet2mxnet_yolov4.py", line 437, in run
    net.load_weights(load_param_name)
  File "/darknet/convert_model_darknet2mxnet_yolov4.py", line 409, in load_weights
    ptr = set_data(module, ptr)
  File "/darknet/convert_model_darknet2mxnet_yolov4.py", line 391, in set_data
    conv_weights = weights[ptr:ptr +num_weights]
  File "/usr/local/lib/python3.7/dist-packages/mxnet/ndarray/ndarray.py", line 511, in __getitem__
    return self._get_nd_basic_indexing(key)
  File "/usr/local/lib/python3.7/dist-packages/mxnet/ndarray/ndarray.py", line 792, in _get_nd_basic_indexing
    return self._slice(key.start, key.stop)
  File "/usr/local/lib/python3.7/dist-packages/mxnet/ndarray/ndarray.py", line 907, in _slice
    start, stop, _ = _get_index_range(start, stop, self.shape[0])
  File "/usr/local/lib/python3.7/dist-packages/mxnet/ndarray/ndarray.py", line 2343, in _get_index_range
    raise IndexError('Slicing stop %d exceeds limit of %d' % (stop, length))
IndexError: Slicing stop 40305504 exceeds limit of 39606267

**Environment (please complete the following information):**
 - Server OS: Ubuntu20.04
 - Ymir Version  release-1.0.0
[ymir-executor-out.tar.gz](https://github.com/IndustryEssentials/ymir/files/9075639/ymir-executor-out.tar.gz)

**Comment by phoenix-xhuang** [comment]
it seems an issue related to yolo module converting, try batch size of 64.

**Comment by zandb2009** [comment]
按你说的修改batch 为64后，尺寸还是修改416 我训练了一会，终止训练并要出结果。日志里还是报一样的错。是因为我的显卡 RTX3050 8G 有问题吗? 另外一台12G内存的显卡却可以跑出结果来。

**Comment by phoenix-xhuang** [comment]
https://github.com/IndustryEssentials/ymir-executor#det-yolov4-training
看一下是不是cuda版本问题

**Comment by zandb2009** [comment]
docker里的cuda版本用的是拉下来的版本
95 -max_batches 20000 -dont_show
 CUDA-version: 10010 (11060), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1
 OpenCV version: 3.2.0
 CUDNN_HALF=1
 0 : compute_capability = 860, cudnn_half = 1, GPU: NVIDIA GeForce RTX 3050

CUDA 应该是10.01的版本；

我用命令nvidia-smi显示
 NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6

如何判断我CUDA版本是不是有问题呢？

**Comment by phoenix-xhuang** [comment]
看上上面提供的链接，里面有提到30XX硬件在10版本的cuda下会有问题

**Comment by zandb2009** [comment]
是的，我用里面cuda11.2的Dockerfile打镜像验证可以了。谢谢！
